source 'https://rubygems.org'

gem "sass", "~>3.3.0"
gem 'compass', '~> 1.0.0.alpha.19'
gem "breakpoint", "~>2.4.0"
gem 'singularitygs', '~> 1.2.0'
gem 'singularity-extras', '~> 1.0.0.alpha.3'
gem 'toolkit', '~>2.0'
gem 'modular-scale', '~> 2.0.4'
gem 'sass-globbing', '~> 1.1.0'